name: cruise_blade
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  google_fonts: ^4.0.0
  hexcolor: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  path_provider: ^2.0.12
  provider: ^6.0.1
  sleek_circular_slider: ^2.0.1
  tmdb_api: ^2.1.4
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
