// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGV2uthZVZZ5qn-GZt2SBayh3UkvgxZU',
    appId: '1:124467887634:web:616e215209011f416ea2cb',
    messagingSenderId: '124467887634',
    projectId: 'cruiseblaze',
    authDomain: 'cruiseblaze.firebaseapp.com',
    storageBucket: 'cruiseblaze.appspot.com',
    measurementId: 'G-YPFWXT8T5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AzrKoEfPLeYY0Ijx7o7Mcf9lHBuMO4I',
    appId: '1:124467887634:android:4fdaf609af0a05e06ea2cb',
    messagingSenderId: '124467887634',
    projectId: 'cruiseblaze',
    storageBucket: 'cruiseblaze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlpyY3_oM6HCL0dnZMmnq7vHvdzItd5xM',
    appId: '1:124467887634:ios:742ac81c49ef037d6ea2cb',
    messagingSenderId: '124467887634',
    projectId: 'cruiseblaze',
    storageBucket: 'cruiseblaze.appspot.com',
    androidClientId: '124467887634-d76kvqmeimu4o63iduevvuu1979gp3os.apps.googleusercontent.com',
    iosClientId: '124467887634-gfuqvs4q1rilp1us6iadtn6iqps7us72.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruiseBlade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlpyY3_oM6HCL0dnZMmnq7vHvdzItd5xM',
    appId: '1:124467887634:ios:742ac81c49ef037d6ea2cb',
    messagingSenderId: '124467887634',
    projectId: 'cruiseblaze',
    storageBucket: 'cruiseblaze.appspot.com',
    androidClientId: '124467887634-d76kvqmeimu4o63iduevvuu1979gp3os.apps.googleusercontent.com',
    iosClientId: '124467887634-gfuqvs4q1rilp1us6iadtn6iqps7us72.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruiseBlade',
  );
}
